//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.06 at 05:57:55 PM BST 
//


package com.dao;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="APPLICABILITY">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TOPIC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MESSAGE_SEQUENCE_NUMBER" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RETURN_DETAILS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EDIFACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicability",
    "returndetails"
})
@XmlRootElement(name = "VISIT_ENGINEER_RETURN")
public class VISITENGINEERRETURN {

    @XmlElement(name = "APPLICABILITY", required = true)
    protected VISITENGINEERRETURN.APPLICABILITY applicability;
    @XmlElement(name = "RETURN_DETAILS", required = true)
    protected VISITENGINEERRETURN.RETURNDETAILS returndetails;

    /**
     * Gets the value of the applicability property.
     * 
     * @return
     *     possible object is
     *     {@link VISITENGINEERRETURN.APPLICABILITY }
     *     
     */
    public VISITENGINEERRETURN.APPLICABILITY getAPPLICABILITY() {
        return applicability;
    }

    /**
     * Sets the value of the applicability property.
     * 
     * @param value
     *     allowed object is
     *     {@link VISITENGINEERRETURN.APPLICABILITY }
     *     
     */
    public void setAPPLICABILITY(VISITENGINEERRETURN.APPLICABILITY value) {
        this.applicability = value;
    }

    /**
     * Gets the value of the returndetails property.
     * 
     * @return
     *     possible object is
     *     {@link VISITENGINEERRETURN.RETURNDETAILS }
     *     
     */
    public VISITENGINEERRETURN.RETURNDETAILS getRETURNDETAILS() {
        return returndetails;
    }

    /**
     * Sets the value of the returndetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link VISITENGINEERRETURN.RETURNDETAILS }
     *     
     */
    public void setRETURNDETAILS(VISITENGINEERRETURN.RETURNDETAILS value) {
        this.returndetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TOPIC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MESSAGE_SEQUENCE_NUMBER" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "topic",
        "messagesequencenumber"
    })
    public static class APPLICABILITY {

        @XmlElement(name = "TOPIC", required = true)
        protected String topic;
        @XmlElement(name = "MESSAGE_SEQUENCE_NUMBER")
        protected long messagesequencenumber;

        /**
         * Gets the value of the topic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTOPIC() {
            return topic;
        }

        /**
         * Sets the value of the topic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTOPIC(String value) {
            this.topic = value;
        }

        /**
         * Gets the value of the messagesequencenumber property.
         * 
         */
        public long getMESSAGESEQUENCENUMBER() {
            return messagesequencenumber;
        }

        /**
         * Sets the value of the messagesequencenumber property.
         * 
         */
        public void setMESSAGESEQUENCENUMBER(long value) {
            this.messagesequencenumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EDIFACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "edifact"
    })
    public static class RETURNDETAILS {

        @XmlElement(name = "EDIFACT", required = true)
        protected String edifact;

        /**
         * Gets the value of the edifact property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEDIFACT() {
            return edifact;
        }

        /**
         * Sets the value of the edifact property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEDIFACT(String value) {
            this.edifact = value;
        }

    }

}
